name: .NET Core Deploy to IIS

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:

    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.6

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish 
      run: |
        dotnet publish -c Release -o public

    - name: Deploy to IIS
      uses: ChristopheLav/iis-deploy@v1
      with:
        website-name: 'MyWebsite'
        msdeploy-service-url: ${{ secrets.MSDEPLOY_URL }}
        msdeploy-username: ${{ secrets.MSDEPLOY_USERNAME }}
        msdeploy-password: ${{ secrets.MSDEPLOY_PASSWORD }}
        source-path: ./public/*

    # - name: Deploy to IIS
    #   run: |
    #     iisreset /stop
    #     Copy-Item ./public/* C:/inetpub/wwwroot/ -Recurse -Force
    #     iisreset /start
    